[variables]
NODE_ENV = "production"
NODE_VERSION = "20.19.1"

[providers]
node = "20.19.1"

[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmd = "npm ci"

[phases.build]
cmd = "npm run build"

[phases.start]
cmd = "npx serve -s dist -p $PORT"